# Generated by Django 3.2.9 on 2021-11-09 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rpg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('apg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('spg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
