# Generated by Django 3.2.9 on 2021-11-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_player_jersey_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='stats.player'),
        ),
    ]
